/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMat;

import java.awt.GridLayout;
import java.util.Iterator;
import java.util.List;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author axel
 */
public class ConfirmPanel extends javax.swing.JPanel {

    private IMatModel model;
    private MainFrame frame;
    /**
     * Creates new form ConfirmPanel
     */
    public ConfirmPanel(IMatModel model) {
        
        this.model = model;
        initComponents();    
        this.setBackground(Constants.BACKGROUND_COLOR);
        
        List<ShoppingItem> items = model.getItems();
        this.shoppingCartPanel.setLayout(new GridLayout(Math.max(9,items.size()), 1));
        Iterator<ShoppingItem> it = items.iterator();
        while (it.hasNext()){
            this.shoppingCartPanel.add(new SmallShoppingCartComponentPanel(it.next()));
        }
        
        cardComboBox.setSelectedItem(model.getCardType());
        cardNumberTextLabel.setText(model.getCardNumber());
        yearTextLabel.setText(Integer.toString(model.getValidYear()));
        monthTextLabel.setText(Integer.toString(model.getValidMonth()));
        cvcTextLabel.setText(Integer.toString(model.getVerificationCode()));
        nameTextLabel.setText(model.getFirstName());
        nameTextLabel2.setText(model.getLastName());
        adressTextLabel.setText(model.getAdress());
        postalCodeTextLabel.setText(model.getPostCode());
        emailTextLabel.setText(model.getEmail());
        phoneTextLabel.setText(model.getPhoneNumber());
        mobilePhoneTextLabel.setText(model.getMobilePhoneNumber());
        
    }
    
    public ConfirmPanel(IMatModel model, MainFrame frame){
        this(model);
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        cardCustomerPanel = new javax.swing.JPanel();
        cardCustomerPanel2 = new javax.swing.JPanel();
        cardInformationLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cvcLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        cardComboBox = new javax.swing.JComboBox();
        cardLabel = new javax.swing.JLabel();
        cardNumberTextLabel = new javax.swing.JLabel();
        yearTextLabel = new javax.swing.JLabel();
        monthTextLabel = new javax.swing.JLabel();
        cvcTextLabel = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        postalCodeLabel = new javax.swing.JLabel();
        postalAdressLabel = new javax.swing.JLabel();
        nameTextLabel = new javax.swing.JLabel();
        nameTextLabel2 = new javax.swing.JLabel();
        postalCodeTextLabel = new javax.swing.JLabel();
        adressTextLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        mobilePhoneLabel = new javax.swing.JLabel();
        phoneTextLabel = new javax.swing.JLabel();
        mobilePhoneTextLabel = new javax.swing.JLabel();
        emailTextLabel = new javax.swing.JLabel();
        shoppingCartScrollPane = new javax.swing.JScrollPane();
        shoppingCartPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1000, 600));

        containerPanel.setBackground(Constants.BACKGROUND_COLOR);
        containerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        containerPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        cardCustomerPanel2.setBackground(new java.awt.Color(255, 255, 255));
        cardCustomerPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        cardCustomerPanel2.setRequestFocusEnabled(false);

        cardInformationLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cardInformationLabel.setText("Bekräfta Order");

        jPanel3.setOpaque(false);

        cvcLabel.setText("CVC");

        dateLabel.setText("År");

        cardNumberLabel.setText("Kortnummer");

        cardComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Mastercard" }));
        cardComboBox.setEnabled(false);

        cardLabel.setText("Kort");

        cardNumberTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardNumberTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        cardNumberTextLabel.setText("Kortnumret");
        cardNumberTextLabel.setOpaque(true);
        cardNumberTextLabel.setPreferredSize(new java.awt.Dimension(100, 17));

        yearTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        yearTextLabel.setText("År");
        yearTextLabel.setOpaque(true);

        monthTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        monthTextLabel.setText("Månad");
        monthTextLabel.setOpaque(true);

        cvcTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        cvcTextLabel.setText("jLabel1");
        cvcTextLabel.setOpaque(true);

        dateLabel1.setText("Månad");

        nameLabel.setText("Namn");

        adressLabel.setText("Adress");

        postalCodeLabel.setText("Postnummer");

        postalAdressLabel.setText("Postort");

        nameTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        nameTextLabel.setText("Förnamn");
        nameTextLabel.setOpaque(true);

        nameTextLabel2.setForeground(new java.awt.Color(150, 150, 150));
        nameTextLabel2.setText("Efternamn");
        nameTextLabel2.setOpaque(true);

        postalCodeTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        postalCodeTextLabel.setText("Postnummer");
        postalCodeTextLabel.setOpaque(true);

        adressTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        adressTextLabel.setText("Tvärvägen 20");
        adressTextLabel.setOpaque(true);

        emailLabel.setText("Email");

        phoneLabel.setText("Telefon");

        mobilePhoneLabel.setText("Mobiltelefon");

        phoneTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        phoneTextLabel.setText("070-00000");
        phoneTextLabel.setOpaque(true);

        mobilePhoneTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        mobilePhoneTextLabel.setText("070-00000");
        mobilePhoneTextLabel.setOpaque(true);

        emailTextLabel.setForeground(new java.awt.Color(150, 150, 150));
        emailTextLabel.setText("example@mail.com");
        emailTextLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mobilePhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cvcLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postalCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postalAdressLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobilePhoneTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardNumberTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cvcTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postalCodeTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adressTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardLabel)
                    .addComponent(cardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvcTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvcLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(postalAdressLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postalCodeTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilePhoneTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilePhoneLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardCustomerPanel2Layout = new javax.swing.GroupLayout(cardCustomerPanel2);
        cardCustomerPanel2.setLayout(cardCustomerPanel2Layout);
        cardCustomerPanel2Layout.setHorizontalGroup(
            cardCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCustomerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardCustomerPanel2Layout.createSequentialGroup()
                        .addComponent(cardInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardCustomerPanel2Layout.setVerticalGroup(
            cardCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCustomerPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(cardInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardCustomerPanelLayout = new javax.swing.GroupLayout(cardCustomerPanel);
        cardCustomerPanel.setLayout(cardCustomerPanelLayout);
        cardCustomerPanelLayout.setHorizontalGroup(
            cardCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardCustomerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cardCustomerPanelLayout.setVerticalGroup(
            cardCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardCustomerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        shoppingCartScrollPane.setBackground(Constants.BACKGROUND_COLOR);
        shoppingCartScrollPane.setMinimumSize(new java.awt.Dimension(500, 600));
        shoppingCartScrollPane.setName(""); // NOI18N
        shoppingCartScrollPane.setPreferredSize(new java.awt.Dimension(500, 600));

        shoppingCartPanel.setBackground(Constants.BACKGROUND_COLOR);
        shoppingCartPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        shoppingCartPanel.setPreferredSize(new java.awt.Dimension(500, 600));

        javax.swing.GroupLayout shoppingCartPanelLayout = new javax.swing.GroupLayout(shoppingCartPanel);
        shoppingCartPanel.setLayout(shoppingCartPanelLayout);
        shoppingCartPanelLayout.setHorizontalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        shoppingCartPanelLayout.setVerticalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        shoppingCartScrollPane.setViewportView(shoppingCartPanel);

        jPanel1.setBackground(Constants.BACKGROUND_COLOR);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 50));

        confirmButton.setBackground(Constants.HEADER_COLOR);
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Bekräfta");
        confirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        confirmButton.setPreferredSize(new java.awt.Dimension(50, 25));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backButton.setBackground(Constants.HEADER_COLOR);
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Bakåt");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton.setPreferredSize(new java.awt.Dimension(50, 25));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(cardCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                    .addComponent(shoppingCartScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(shoppingCartScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        model.placeOrder(true);
        if(frame != null){
            this.shoppingCartPanel.removeAll();
            frame.setEndingCard("buy");
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        frame.setFeatureCard("checkoutCard");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel adressTextLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox cardComboBox;
    private javax.swing.JPanel cardCustomerPanel;
    private javax.swing.JPanel cardCustomerPanel2;
    private javax.swing.JLabel cardInformationLabel;
    private javax.swing.JLabel cardLabel;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JLabel cardNumberTextLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel cvcLabel;
    private javax.swing.JLabel cvcTextLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTextLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mobilePhoneLabel;
    private javax.swing.JLabel mobilePhoneTextLabel;
    private javax.swing.JLabel monthTextLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTextLabel;
    private javax.swing.JLabel nameTextLabel2;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneTextLabel;
    private javax.swing.JLabel postalAdressLabel;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JLabel postalCodeTextLabel;
    private javax.swing.JPanel shoppingCartPanel;
    private javax.swing.JScrollPane shoppingCartScrollPane;
    private javax.swing.JLabel yearTextLabel;
    // End of variables declaration//GEN-END:variables
}
