/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMat;

import java.awt.GridLayout;
import java.util.Iterator;
import java.util.List;
import se.chalmers.ait.dat215.project.ProductCategory;

/**
 *
 * @author axel
 */
public class ResultPanel extends javax.swing.JPanel {
    private IMatModel model;
    private ProductCategory pc;
    
    /**
     * Creates new form ResultPanel
     */
    public ResultPanel(ProductCategory pc, IMatModel model) {
        this.pc = pc;
        this.model = model;
        initComponents();
        
        List<ProductPanel> products = model.getProductPanels(pc);
        Iterator<ProductPanel> it = products.iterator();
        this.resultPanel.setLayout(new GridLayout((products.size() +3)/4, 4));
        while(it.hasNext()){
            this.resultPanel.add(it.next());
        }
    }
    
    public ResultPanel(List<ProductPanel> products, IMatModel model){
        this.pc = pc;
        this.model = model;
        initComponents();
        
        Iterator<ProductPanel> it = products.iterator();
        this.resultPanel.setLayout(new GridLayout((products.size() +3)/4, 4));
        while(it.hasNext()){
            this.resultPanel.add(it.next());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultScrollPanel = new javax.swing.JScrollPane();
        resultPanel = new javax.swing.JPanel();

        setOpaque(false);

        resultScrollPanel.setOpaque(false);

        resultPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        resultScrollPanel.setViewportView(resultPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultScrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultScrollPanel)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel resultPanel;
    private javax.swing.JScrollPane resultScrollPanel;
    // End of variables declaration//GEN-END:variables
}
