/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMat;

import java.awt.GridLayout;
import java.util.Iterator;
import java.util.List;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.CartEvent;
import se.chalmers.ait.dat215.project.ShoppingCartListener;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Joel
 */
public class ShoppingCartPanel extends javax.swing.JPanel implements ShoppingCartComponentListener {
    
    private final IMatModel model;
    private MainFrame frame;

    /**
     * Creates new form ShoppingCartPanel
     */
    public ShoppingCartPanel(IMatModel model, ShoppingCartComponentListener sccl){
        this.model = model;
        initComponents();
        
        List<ShoppingItem> items = model.getItems();
        this.itemPanel.setLayout(new GridLayout(Math.max(6,items.size()), 1));
        Iterator<ShoppingItem> it = items.iterator();
        ShoppingCartComponentPanel tempPanel;
        while (it.hasNext()){
            tempPanel = new ShoppingCartComponentPanel(it.next(), this);
            this.itemPanel.add(tempPanel);
            tempPanel.addShoppingCartComponentListener(this);
            tempPanel.addShoppingCartComponentListener(sccl);
        }
        
        this.costLabel.setText(model.getTotalCost() + " kr");
    }
    
    public ShoppingCartPanel(IMatModel model, ShoppingCartComponentListener sccl, MainFrame frame) {
        this(model, sccl);
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemScrollPanel = new javax.swing.JScrollPane();
        itemPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        totLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(993, 600));
        setOpaque(false);

        itemScrollPanel.setOpaque(false);

        itemPanel.setOpaque(false);

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        itemScrollPanel.setViewportView(itemPanel);

        infoPanel.setOpaque(false);

        nextButton.setBackground(Constants.HEADER_COLOR);
        nextButton.setFont(Constants.BUTTON_FONT);
        nextButton.setBackground(Constants.HEADER_COLOR);
        nextButton.setForeground(Constants.BACKGROUND_COLOR);
        nextButton.setForeground(Constants.BACKGROUND_COLOR);
        nextButton.setText("Gå vidare");
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        totLabel.setFont(Constants.RESULT_FONT);
        totLabel.setText("Totalt:");

        costLabel.setFont(Constants.RESULT_FONT);
        costLabel.setText("cost");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addComponent(totLabel)
                        .addGap(69, 69, 69)
                        .addComponent(costLabel)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(totLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemScrollPanel)
                .addContainerGap())
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void removeCartComponentPanel(ShoppingCartComponentPanel s){
        this.itemPanel.remove(s);
        model.removeItemFromCart(s.getShoppingItem());
        this.itemPanel.repaint();
    }
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (frame != null && (!model.getItems().isEmpty()))
            frame.setFeatureCard("checkoutCard");
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JScrollPane itemScrollPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel totLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void shoppingCartComponentChanged(ShoppingItem item, boolean itemAdded) {
        this.costLabel.setText(model.getTotalCost() + " kr");
    }
}
